"""empty message

Revision ID: 8fa4cbd2c491
Revises: 14acee324a37
Create Date: 2017-07-09 15:58:29.400192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fa4cbd2c491'
down_revision = '14acee324a37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('categories_files',
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], )
    )
    op.add_column('file', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('file', sa.Column('defined_name', sa.String(length=255), nullable=False))
    op.add_column('file', sa.Column('expiration_date', sa.DateTime(), nullable=False))
    op.add_column('file', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'file', 'category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'file', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_column('file', 'user_id')
    op.drop_column('file', 'expiration_date')
    op.drop_column('file', 'defined_name')
    op.drop_column('file', 'category_id')
    op.drop_table('categories_files')
    op.drop_table('roles_users')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
